name: Metrics

on:
  schedule:
    - cron: '0 0 * * *' # S'executa una vegada al dia.
  workflow_dispatch: # Permet executar-lo manualment.
  push:
    branches:
      - main # O quan es faça un push a la branca main.

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
